# Generated by Django 5.1 on 2024-08-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieranking', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
